<a href="https://colab.research.google.com/github/sirimadhuri02/CognitiveScienceAndAnalytics/blob/StemmingandLemmatization/Ambiguity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import nltk
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.corpus import wordnet

# Downloads
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('punkt_tab')
try:
    nltk.download('averaged_perceptron_tagger_eng')
except:
    nltk.download('averaged_perceptron_tagger')

# POS explanation dictionary
pos_explanations = {
    "NN": "Noun, singular",
    "NNS": "Noun, plural",
    "NNP": "Proper noun, singular",
    "NNPS": "Proper noun, plural",
    "VB": "Verb, base form",
    "VBD": "Verb, past tense",
    "VBG": "Verb, gerund/present participle",
    "VBN": "Verb, past participle",
    "VBP": "Verb, non-3rd person singular present",
    "VBZ": "Verb, 3rd person singular present",
    "JJ": "Adjective",
    "JJR": "Adjective, comparative",
    "JJS": "Adjective, superlative",
    "RB": "Adverb",
    "RBR": "Adverb, comparative",
    "RBS": "Adverb, superlative",
    "PRP": "Pronoun",
    "PRP$": "Possessive pronoun",
    "DT": "Determiner",
    "IN": "Preposition",
    "CC": "Coordinating conjunction",
    "UH": "Interjection"
}

# POS mapping for WordNet lemmatizer
def get_wordnet_pos(treebank_tag):
    if treebank_tag.startswith('J'):
        return wordnet.ADJ
    elif treebank_tag.startswith('V'):
        return wordnet.VERB
    elif treebank_tag.startswith('N'):
        return wordnet.NOUN
    elif treebank_tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

# Initialize tools
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

# Sentences
sentence1 = "The manager managing the team effeciently was praised for his leadership."
sentence2 = "After attending the meetings, she recorded the minutes and noted important decisions"
sentence3 = "The cats chasing the mice were chased by other animals in the wild"
sentence4 = "the lead researcher leads the team toward finding new solutions to lead contamination"
sentence5 = "Her readings about the reading comprehention helped her understand the material better."

sentences = [sentence1, sentence2, sentence3, sentence4, sentence5]

# Process each sentence and assign to separate DataFrames
def process_sentence(sentence):
    words = nltk.word_tokenize(sentence)
    pos_tags = nltk.pos_tag(words)
    results = []
    for word, pos in pos_tags:
        if word.isalpha():
            stemmed = stemmer.stem(word)
            lemma_simple = lemmatizer.lemmatize(word)
            lemma_pos = lemmatizer.lemmatize(word, get_wordnet_pos(pos))
            pos_expl = pos_explanations.get(pos, "Other/Unknown")
            results.append([word, pos, pos_expl, stemmed, lemma_simple, lemma_pos])
    df = pd.DataFrame(
        results,
        columns=["Word", "POS", "POS Explanation", "Stemming", "Lemma (No POS)", "Lemma (With POS)"]
    )
    return df

df1 = process_sentence(sentence1)
df2 = process_sentence(sentence2)
df3 = process_sentence(sentence3)
df4 = process_sentence(sentence4)
df5 = process_sentence(sentence5)

# Display each DataFrame
print("\n=== DataFrame for Sentence 1 ===")
display(df1)

print("\n=== DataFrame for Sentence 2 ===")
display(df2)

print("\n=== DataFrame for Sentence 3 ===")
display(df3)

print("\n=== DataFrame for Sentence 4 ===")
display(df4)

print("\n=== DataFrame for Sentence 5 ===")
display(df5)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

=== DataFrame for Sentence 1 ===

,Word,POS,POS Explanation,Stemming,Lemma (No POS),Lemma (With POS)
0,The,DT,Determiner,the,The,The
1,manager,NN,"Noun, singular",manag,manager,manager
2,managing,VBG,"Verb, gerund/present participle",manag,managing,manage
3,the,DT,Determiner,the,the,the
4,team,NN,"Noun, singular",team,team,team
5,effeciently,RB,Adverb,effeci,effeciently,effeciently
6,was,VBD,"Verb, past tense",wa,wa,be
7,praised,VBN,"Verb, past participle",prais,praised,praise
8,for,IN,Preposition,for,for,for
9,his,PRP$,Possessive pronoun,hi,his,his
10,leadership,NN,"Noun, singular",leadership,leadership,leadership

=== DataFrame for Sentence 2 ===

,Word,POS,POS Explanation,Stemming,Lemma (No POS),Lemma (With POS)
0,After,IN,Preposition,after,After,After
1,attending,VBG,"Verb, gerund/present participle",attend,attending,attend
2,the,DT,Determiner,the,the,the
3,meetings,NNS,"Noun, plural",meet,meeting,meeting
4,she,PRP,Pronoun,she,she,she
5,recorded,VBD,"Verb, past tense",record,recorded,record
6,the,DT,Determiner,the,the,the
7,minutes,NNS,"Noun, plural",minut,minute,minute
8,and,CC,Coordinating conjunction,and,and,and
9,noted,VBD,"Verb, past tense",note,noted,note
10,important,JJ,Adjective,import,important,important
11,decisions,NNS,"Noun, plural",decis,decision,decision

=== DataFrame for Sentence 3 ===

,Word,POS,POS Explanation,Stemming,Lemma (No POS),Lemma (With POS)
0,The,DT,Determiner,the,The,The
1,cats,NNS,"Noun, plural",cat,cat,cat
2,chasing,VBG,"Verb, gerund/present participle",chase,chasing,chase
3,the,DT,Determiner,the,the,the
4,mice,NN,"Noun, singular",mice,mouse,mouse
5,were,VBD,"Verb, past tense",were,were,be
6,chased,VBN,"Verb, past participle",chase,chased,chase
7,by,IN,Preposition,by,by,by
8,other,JJ,Adjective,other,other,other
9,animals,NNS,"Noun, plural",anim,animal,animal
10,in,IN,Preposition,in,in,in
11,the,DT,Determiner,the,the,the
12,wild,NN,"Noun, singular",wild,wild,wild

=== DataFrame for Sentence 4 ===

,Word,POS,POS Explanation,Stemming,Lemma (No POS),Lemma (With POS)
0,the,DT,Determiner,the,the,the
1,lead,NN,"Noun, singular",lead,lead,lead
2,researcher,NN,"Noun, singular",research,researcher,researcher
3,leads,VBZ,"Verb, 3rd person singular present",lead,lead,lead
4,the,DT,Determiner,the,the,the
5,team,NN,"Noun, singular",team,team,team
6,toward,IN,Preposition,toward,toward,toward
7,finding,VBG,"Verb, gerund/present participle",find,finding,find
8,new,JJ,Adjective,new,new,new
9,solutions,NNS,"Noun, plural",solut,solution,solution
10,to,TO,Other/Unknown,to,to,to
11,lead,VB,"Verb, base form",lead,lead,lead
12,contamination,NN,"Noun, singular",contamin,contamination,contamination

=== DataFrame for Sentence 5 ===

,Word,POS,POS Explanation,Stemming,Lemma (No POS),Lemma (With POS)
0,Her,PRP$,Possessive pronoun,her,Her,Her
1,readings,NNS,"Noun, plural",read,reading,reading
2,about,IN,Preposition,about,about,about
3,the,DT,Determiner,the,the,the
4,reading,NN,"Noun, singular",read,reading,reading
5,comprehention,NN,"Noun, singular",comprehent,comprehention,comprehention
6,helped,VBD,"Verb, past tense",help,helped,help
7,her,PRP,Pronoun,her,her,her
8,understand,VB,"Verb, base form",understand,understand,understand
9,the,DT,Determiner,the,the,the
10,material,NN,"Noun, singular",materi,material,material
11,better,RBR,"Adverb, comparative",better,better,well

In [ ]:
# Sentences
sentence6 = "Flying planes can be dangerous if the weather changes suddenly."
sentence7 = "The old man the boats near the shore during the storm."
sentence8 = "She saw her duck before it jumped into the water."
sentence9 = "the band saw the saw and decided to fix it immediately."
sentence10 = "I will book the book before the event begins. "
df6 = process_sentence(sentence6)
df7 = process_sentence(sentence7)
df8 = process_sentence(sentence8)
df9 = process_sentence(sentence9)
df10 = process_sentence(sentence10)

# Display each DataFrame
print("\n=== DataFrame for Sentence 6 ===")
display(df6)

print("\n=== DataFrame for Sentence 7 ===")
display(df7)

print("\n=== DataFrame for Sentence 8 ===")
display(df8)

print("\n=== DataFrame for Sentence 9 ===")
display(df9)

print("\n=== DataFrame for Sentence 10 ===")
display(df10)

=== DataFrame for Sentence 6 ===

,Word,POS,POS Explanation,Stemming,Lemma (No POS),Lemma (With POS)
0,Flying,VBG,"Verb, gerund/present participle",fli,Flying,Flying
1,planes,NNS,"Noun, plural",plane,plane,plane
2,can,MD,Other/Unknown,can,can,can
3,be,VB,"Verb, base form",be,be,be
4,dangerous,JJ,Adjective,danger,dangerous,dangerous
5,if,IN,Preposition,if,if,if
6,the,DT,Determiner,the,the,the
7,weather,NN,"Noun, singular",weather,weather,weather
8,changes,VBZ,"Verb, 3rd person singular present",chang,change,change
9,suddenly,RB,Adverb,suddenli,suddenly,suddenly

=== DataFrame for Sentence 7 ===

      Word  POS POS Explanation Stemming Lemma (No POS) Lemma (With POS)
0      The   DT      Determiner      the            The              The
1      old   JJ       Adjective      old            old              old
2      man   NN  Noun, singular      man            man              man
3      the   DT      Determiner      the            the              the
4    boats  NNS    Noun, plural     boat           boat             boat
5     near   IN     Preposition     near           near             near
6      the   DT      Determiner      the            the              the
7    shore   NN  Noun, singular    shore          shore            shore
8   during   IN     Preposition     dure         during           during
9      the   DT      Determiner      the            the              the
10   storm   NN  Noun, singular    storm          storm            storm

=== DataFrame for Sentence 8 ===

     Word  POS   POS Explanation Stemming Lemma (No POS) Lemma (With POS)
0     She  PRP           Pronoun      she            She              She
1     saw  VBD  Verb, past tense      saw            saw              saw
2     her  PRP           Pronoun      her            her              her
3    duck   NN    Noun, singular     duck           duck             duck
4  before   IN       Preposition    befor         before           before
5      it  PRP           Pronoun       it             it               it
6  jumped  VBD  Verb, past tense     jump         jumped             jump
7    into   IN       Preposition     into           into             into
8     the   DT        Determiner      the            the              the
9   water   NN    Noun, singular    water          water            water

=== DataFrame for Sentence 9 ===

,Word,POS,POS Explanation,Stemming,Lemma (No POS),Lemma (With POS)
0,the,DT,Determiner,the,the,the
1,band,NN,"Noun, singular",band,band,band
2,saw,VBD,"Verb, past tense",saw,saw,saw
3,the,DT,Determiner,the,the,the
4,saw,NN,"Noun, singular",saw,saw,saw
5,and,CC,Coordinating conjunction,and,and,and
6,decided,VBD,"Verb, past tense",decid,decided,decide
7,to,TO,Other/Unknown,to,to,to
8,fix,VB,"Verb, base form",fix,fix,fix
9,it,PRP,Pronoun,it,it,it
10,immediately,RB,Adverb,immedi,immediately,immediately

=== DataFrame for Sentence 10 ===

,Word,POS,POS Explanation,Stemming,Lemma (No POS),Lemma (With POS)
0,I,PRP,Pronoun,i,I,I
1,will,MD,Other/Unknown,will,will,will
2,book,NN,"Noun, singular",book,book,book
3,the,DT,Determiner,the,the,the
4,book,NN,"Noun, singular",book,book,book
5,before,IN,Preposition,befor,before,before
6,the,DT,Determiner,the,the,the
7,event,NN,"Noun, singular",event,event,event
8,begins,VBZ,"Verb, 3rd person singular present",begin,begin,begin